#!/usr/bin/env bash
# Script displays information about subdomains
# shellcheck disable=SC2086

get_info()
{
	printf "The subdomain %s is a " "$2"
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
	printf " record and points to "
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
	echo ""
}

if [ -z "$2" ];
then
	for sub_dom in "www" "lb-01" "web-01" "web-02"
	do
		get_info "$1" "$sub_dom"
	done
else
	get_info "$1" "$2"
fi
