#!/usr/bin/env bash
# Installing nginx and querying "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo ufw enable
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
