#!/usr/bin/env bash
# Installing nginx and querying "Hello World"

apt-get update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
