#!/usr/bin/env bash
# Script to install and config an Nginx server
#       Nginx should be listening on port 80
#       /redirect_me should redirect to a "301 Moved Permanently" error

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/;\n\t}\n"


sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "42i $ADD301_REDIRECT" /etc/nginx/sites-available/default #add at line 42
sudo service nginx start
