#!/usr/bin/env bash
# Script to install and config an Nginx server
#       Nginx should be listening on port 80
#       /redirect_me should redirect to a "301 Moved Permanently" error
#   custom 404 page

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/;\n\t}\n"
ADD404_NOTFOUND="\\\terror_page 404 /my_404.html;\n\tlocation = /my_404.html {\n\t\troot /usr/share/nginx/html; \n\t\tinternal;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "42i $ADD301_REDIRECT" /etc/nginx/sites-available/default #add at line 42

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/my_404.html
sudo sed -i "46i $ADD404_NOTFOUND" /etc/nginx/sites-available/default #add at line 46

sudo service nginx restart
