#!/usr/bin/env bash
# Script install and configure HaProxy load balancer to use the roundrobin algo to share request

sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy=2.0.\*

sudo service haproxy start
# enabled to start at boot
echo "ENABLED=1" | sudo tee /etc/haproxy/default/haproxy

# backup init config
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

config = "
frontend my_frontend
    bind *:80
    mode http
    default_backend my_backend

backend my_backend
    balance roundrobin
    server 529356-web-01 52.87.219.34:80 check
    server 529356-web-02 100.25.132.43:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
