#!/usr/bin/env bash
# Script debugs "connection refused" to port 80 by installing a web serve
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
