#!/usr/bin/env bash
# Script installs nginx and kills the process after being called
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo rm /run/nginx.pid
