#!/usr/bin/env bash
# Script setup firewall and block allow incoming traffic but accept incoming traffic on:
#	* port 80 http
#	* port 22 ssh
#	* port 443 https

sudo apt-get update
sudo apt-get -y install ufw
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
